/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ClientEvent = SessionStart | TurnStart | TurnStop | UtteranceOverrideLang | SidesUpdate | Ping;
export type Type = "session.start";
export type Protocol = number;
export type Rate = number;
export type Format = string;
export type Lang = string;
export type Type1 = "turn.start";
export type Side = "A" | "B";
export type Type2 = "turn.stop";
export type Type3 = "utterance.override_lang";
export type UtteranceId = number;
export type Lang1 = "ja" | "en" | "vi";
export type Type4 = "sides.update";
export type Type5 = "ping";
export type T = number;

export interface SessionStart {
  type?: Type;
  protocol: Protocol;
  audio: AudioConfig;
  sides: Sides;
  [k: string]: unknown;
}
export interface AudioConfig {
  rate: Rate;
  format: Format;
  [k: string]: unknown;
}
export interface Sides {
  [k: string]: SideConfig;
}
export interface SideConfig {
  lang: Lang;
  [k: string]: unknown;
}
export interface TurnStart {
  type?: Type1;
  side: Side;
  [k: string]: unknown;
}
export interface TurnStop {
  type?: Type2;
  [k: string]: unknown;
}
export interface UtteranceOverrideLang {
  type?: Type3;
  utterance_id: UtteranceId;
  lang: Lang1;
  [k: string]: unknown;
}
export interface SidesUpdate {
  type?: Type4;
  sides: Sides1;
  [k: string]: unknown;
}
export interface Sides1 {
  [k: string]: SideConfig;
}
export interface Ping {
  type?: Type5;
  t: T;
  [k: string]: unknown;
}
