/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ServerEvent =
  SessionReady | Vad | AsrPartial | AsrFinal | MtDelta | MtFinal | UtteranceMetrics | ErrorEvent | Pong;
export type Type = "session.ready";
export type SessionId = string;
export type Profile = string;
export type PackRevision = string;
export type Type1 = "vad";
export type Side = "A" | "B";
export type Speaking = boolean;
export type Type2 = "asr.partial";
export type UtteranceId = number;
export type Side1 = "A" | "B";
export type Text = string;
export type Lang = ("ja" | "en" | "vi") | null;
export type Type3 = "asr.final";
export type UtteranceId1 = number;
export type Side2 = "A" | "B";
export type Text1 = string;
export type Lang1 = "ja" | "en" | "vi";
export type Uncertain = boolean;
export type AudioMs = number;
export type Type4 = "mt.delta";
export type UtteranceId2 = number;
export type Target = "ja" | "en" | "vi";
export type Delta = string;
export type Type5 = "mt.final";
export type UtteranceId3 = number;
export type Target1 = "ja" | "en" | "vi";
export type Text2 = string;
export type Type6 = "utterance.metrics";
export type UtteranceId4 = number;
export type AsrMs = number;
export type E2EMs = number;
export type Type7 = "error";
export type Code = string;
export type Message = string;
export type UtteranceId5 = number | null;
export type Retryable = boolean;
export type Type8 = "pong";
export type T = number;
export type ServerT = number;

export interface SessionReady {
  type?: Type;
  session_id: SessionId;
  profile: Profile;
  pack_revision: PackRevision;
  models: Models;
  [k: string]: unknown;
}
export interface Models {
  [k: string]: unknown;
}
export interface Vad {
  type?: Type1;
  side: Side;
  speaking: Speaking;
  [k: string]: unknown;
}
export interface AsrPartial {
  type?: Type2;
  utterance_id: UtteranceId;
  side: Side1;
  text: Text;
  lang?: Lang;
  [k: string]: unknown;
}
export interface AsrFinal {
  type?: Type3;
  utterance_id: UtteranceId1;
  side: Side2;
  text: Text1;
  lang: Lang1;
  lang_probs: LangProbs;
  uncertain: Uncertain;
  audio_ms: AudioMs;
  [k: string]: unknown;
}
export interface LangProbs {
  [k: string]: number;
}
export interface MtDelta {
  type?: Type4;
  utterance_id: UtteranceId2;
  target: Target;
  delta: Delta;
  [k: string]: unknown;
}
export interface MtFinal {
  type?: Type5;
  utterance_id: UtteranceId3;
  target: Target1;
  text: Text2;
  [k: string]: unknown;
}
export interface UtteranceMetrics {
  type?: Type6;
  utterance_id: UtteranceId4;
  asr_ms: AsrMs;
  mt_ms: MtMs;
  e2e_ms: E2EMs;
  [k: string]: unknown;
}
export interface MtMs {
  [k: string]: number;
}
export interface ErrorEvent {
  type?: Type7;
  code: Code;
  message: Message;
  utterance_id?: UtteranceId5;
  retryable: Retryable;
  [k: string]: unknown;
}
export interface Pong {
  type?: Type8;
  t: T;
  server_t: ServerT;
  [k: string]: unknown;
}
